
import type { Product, Category } from './types';

export const CATEGORIES: (Category | 'All')[] = ['All', 'Home Decor', 'Fashion', 'Art', 'Accessories'];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Mystic Wall Hanging',
    price: 900,
    imageUrl: 'https://picsum.photos/seed/mysticwallhanging/400/400',
    category: 'Home Decor',
  },
  {
    id: 2,
    name: 'Wall Hanging with Floral Patterns',
    price: 650,
    imageUrl: 'https://picsum.photos/seed/flowerartwallhanging/400/400',
    category: 'Home Decor',
  },
  {
    id: 3,
    name: 'Applique Work Umbrella',
    price: 700,
    imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQuuvJPL246UEKVRIlyjdUuqwSADH2KKRXZTVvbl4NwJqe1ArVCwc-uQVDQGbVpkgMbOhWMhJCjc_QUdmsNrCTtkKez03s_AbnREwyXMH-6tbK_7WCaljzn1A',
    category: 'Accessories',
  },
  {
    id: 4,
    name: 'Village Scene Cushion Cover',
    price: 650,
    imageUrl: 'https://itokri.com/cdn/shop/files/3T1A9772_c6b99a12-1cdf-404a-9e04-e12136214a82.jpg?v=1701955563&width=480',
    category: 'Home Decor',
  },
  {
    id: 5,
    name: 'Mythical Scene Artwork',
    price: 2500,
    imageUrl: 'https://i0.wp.com/blogvirasatehind.wordpress.com/wp-content/uploads/2018/08/img_2829.jpg?fit=1200%2C800&ssl=1',
    category: 'Art',
  },
  {
    id: 6,
    name: 'Colourful Tribal Art',
    price: 2500,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL-h-4BYYqkdJr2uwbxCR1rPTznT2cMF7Kvg&s',
    category: 'Art',
  },
  {
    id: 7,
    name: 'Patchwork Dolphin Pillow Cover',
    price: 499,
    imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQLzVpHhuivUza5MQGTN1GSkaVN2xBeRSwVX9m2hFFZ5ho7K-rFs8J4e1lnv4G2uqTkLskTyaPHnhTWaNlBu2rOsXCI1hHjeHq2cFASoo4',
    category: 'Home Decor',
  },
  {
    id: 8,
    name: 'Lord Jagannath Wall Hanging',
    price: 800,
    imageUrl: 'https://m.media-amazon.com/images/I/71OwdgTQfuL._AC_UF1000,1000_QL80_.jpg',
    category: 'Home Decor',
  },
  {
    id: 9,
    name: 'Cotton Sling Bag',
    price: 380,
    imageUrl: 'https://picsum.photos/seed/cottonslingbag/400/400',
    category: 'Fashion',
  },
  {
    id: 10,
    name: 'Cosmetic Pouch',
    price: 299,
    imageUrl: 'https://picsum.photos/seed/cosmeticpouch/400/400',
    category: 'Fashion',
  },
  {
    id: 11,
    name: 'Potli Bag',
    price: 300,
    imageUrl: 'https://picsum.photos/seed/potlibag/400/400',
    category: 'Fashion',
  },
  {
    id: 12,
    name: 'Tribal Family Art Work',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/tribalfamily/400/400',
    category: 'Art',
  },
  {
    id: 13,
    name: 'Toran',
    price: 450,
    imageUrl: 'https://picsum.photos/seed/toran/400/400',
    category: 'Home Decor',
  },
  {
    id: 14,
    name: 'Wall Hanging Storage',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/hangingstorage/400/400',
    category: 'Home Decor',
  },
  {
    id: 15,
    name: 'Hanging Lamp',
    price: 450,
    imageUrl: 'https://picsum.photos/seed/hanginglamp/400/400',
    category: 'Home Decor',
  },
  {
    id: 16,
    name: 'Dokra Candle Stand',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/candlestand/400/400',
    category: 'Home Decor',
  },
  {
    id: 17,
    name: 'Dokra Pen Stand',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/penstand/400/400',
    category: 'Home Decor',
  },
  {
    id: 18,
    name: 'Dokra Umbrella Keychain',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/umbrellakeychain/400/400',
    category: 'Accessories',
  },
  {
    id: 19,
    name: 'Dokra Guitar Keychain',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/guitarkeychain/400/400',
    category: 'Accessories',
  },
  {
    id: 20,
    name: 'Dokra Leaf Ring',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/leafring/400/400',
    category: 'Fashion',
  },
  {
    id: 21,
    name: 'Dokra Butterfly Ring',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/butterflyring/400/400',
    category: 'Fashion',
  },
  {
    id: 22,
    name: 'Dokra Horse Decor',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/horsedecor/400/400',
    category: 'Home Decor',
  },
];
